### ISSUE TITLE
How to build a mocap system?

### ISSUE THREAD

**Issue by FishHe** [sziccardi/MoCap#1]
Hi,
I'm looking for a marker-based motion capture system, and find this awesome work. I have many questions, could you please share your e-mail or skype-id with me?

**Comment by sziccardi** [comment]
Hello!
Unfortunately this is not a complete system, simply an investigation into the theoretical underpinnings of marker-based optical motion capture. Though I would be happy to answer any questions you may have. You can contact me at shelbyziccardi@gmail.com.
